language: c
env:
  - ARDUINO_VERSION=1.8.10
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$ARDUINO_VERSION-linux64.tar.xz
  - tar xf arduino-$ARDUINO_VERSION-linux64.tar.xz
  - sudo mv arduino-$ARDUINO_VERSION /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/TheThingsNode
  - arduino --install-library "DHT sensor library:1.3.7,Adafruit Unified Sensor:1.0.2,TheThingsNetwork:2.5.16,TheThingsNode:2.0.7"
  - git clone https://github.com/sparkfun/arduino_boards /tmp/sparkfun
  - mv /tmp/sparkfun/sparkfun /usr/local/share/arduino/hardware/sparkfun
  - mkdir 
  - wget https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/archive/master.zip
  - unzip master.zip -d temp
  - mv temp /usr/local/share/arduino/libraries/TTGO_TWatch_Library
script:
  - arduino --verify --board sparkfun:avr:promicro:cpu=8MHzatmega32U4 thethingsnode.ino
notifications:
  email:
    on_success: change
    on_failure: change
